name: tib_api
description: A reverse engineered API for the TIB (Transportes de las Islas Baleares) public transport service.
version: 0.5.9
repository: https://github.com/open-transport-mallorca/tib_api
issue_tracker: https://github.com/open-transport-mallorca/tib_api/issues

environment:
  sdk: ^3.0.0

dependencies:
  chaleno: ^0.0.8
  dart_rss: ^3.0.3
  http: ^1.2.1
  latlong2: ^0.9.1
  web_socket_channel: ^2.4.5
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
