name: Dart Test and Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Format code
        run: dart format --set-exit-if-changed .

      - name: Get dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze code
        run: dart analyze
